services:
  #django app
  backend_auth:
    container-name: py_ms_auth
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    
  #event queue kafka
  queue_auth:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db

  #postgres database
  db:
    image: postgres:12
    container_name: psql_ms_auth
    restart: always
    environment:
      POSTGRES_DB: py_auth_db
      POSTGRES_USER: onlypy
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql
    

  #REDIS CACHE
  redis:
    image: redis
    container_name: redis_ms_auth
    ports:
      - 6379:6379

